### PR TITLE
Episode name expression fix

### LINKED ISSUE #704: Local files are not getting indexed
**Describe the bug**
I have local files stored in my external hard drive, but Stremio is not able to index files even though files are downloaded and contains the same naming as the one that shows when I choose an episode from the list. 

I can confirm that I have two TV shows. They both downloaded from the same source and all files are stored in the same hard drive.
I can individually find files when I search from the Start Menu (Windows 11) and both files of both TV shows are being listed.
I can confirm that 1 TV show files are being shows on Stremio as I watch though Stremio, but the other one doesn't register files.

The file path `"F:\Dizi\Stargate SG-1 (1994) Season 1-10 S01-10 (1080p BluRay x265 HEVC 10bit DD 5.1 EDGE2020)\Season 1\Stargate SG-1 - S01E01-E02 - Children of the Gods (1080p x265 EDGE2020).mkv"`

**To Reproduce**
1. Download `Stargate-SG-1-1997-Season-1-10-S01-10-1080p-BluRay-x265-HEVC-10bit-DD-5-1-EDGE2020`
2. Move files to an external hard drive
3. Expect them to be indexed

**Expected behavior**
Files should be listed under local files in Stremio
image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Version [e.g. 22] Stremio 4.4.165

**Smartphone (please complete the following information):**

**TV (please complete the following information):**
 - Device: [e.g. Mi Box S 4K, Samsung 50Q64B]
 - OS: [e.g. Android TV, Tizen (Samsung)]
 - Version [e.g. 2.0.0]

**Additional context**
I have tried restarting, re-indexing
image

### PR DESCRIPTION
**Pull request by seahindeniz**
The expression was matching with `EDGE2020` as episode 20, so this PR fixes that
https://regex101.com/r/CZURT7/1

fixes https://github.com/Stremio/stremio-bugs/issues/704

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -104,7 +104,7 @@ function parseVideoName(filePath, options)
                 meta.season = parseInt(seasonMatch[1], 10);
             
             /* TODO: consider the case when a hyphen is used for multiple episodes ; e.g. e1-3 */
-            var episodeMatch = x.match(/E(\d{2})/ig);
+            var episodeMatch = x.match(/(?<=\W|\d)E(\d{2})/ig);
```
Comment (seahindeniz) [inline index.js:107]: It basically expects there's a number or a non-alphanumeric char to be prefixed to `E`. Like `1E` as in `S01E01` or `S01 E01` or `S01-E01`

**Comment by seahindeniz** [comment]
Hi @Ivshti, could you please review the PR?

**Comment by jaruba** [comment]
seems safe to me

**Review by jaruba — APPROVED** [review]

**Comment by jaruba** [comment]
@seahindeniz i can increase the package version but i think only @Ivshti can publish it to npm if that's what you are expecing

**Comment by jaruba** [comment]
@seahindeniz new version is published to npm

**Comment by seahindeniz** [comment]
That cool @jaruba, thank you for merging it so quickly!
